# Generated by Django 3.0.7 on 2020-06-28 08:39

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
